# -*- coding: utf-8 -*-
"""173_day03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sB6uDRAU7uyBW-mzlP1uS9Zv-WNixY1J
"""

import pandas as pd

lst = ['Greek', 'For', 'Greek', 'is', 'portal', 'for', 'greek']
df = pd.DataFrame(lst)

print(df)

import pandas as pd

data = {
    'Name': ['nick', 'krish', 'jack'],
    'Age': [20, 21, 18]
}

df = pd.DataFrame(data)

print(df)

import numpy as np
import statistics as stats

numbers = [10, 20, 20, 30, 40, 50]
mean = np.mean(numbers)
median = np.median(numbers)
mode = stats.mode(numbers)

variance = np.var(numbers)
std_dev = np.std(numbers)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)
result = arr * 2
print("Element-wise multiplication:", result)

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose of A:\n", A.T)

import numpy as np

random_arr = np.random.rand(10)

print("Random Array:", random_arr)
print("Mean:", np.mean(random_arr))
print("Standard Deviation:", np.std(random_arr))
print("Minimum:", np.min(random_arr))
print("Maximum:", np.max(random_arr))

import numpy as np
from scipy import stats

sample = np.array([12, 15, 14, 10, 18, 20, 22])
mean = stats.tmean(sample)
print("Mean (SciPy):", mean)
t_stat, p_value = stats.ttest_1samp(sample, 15)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

from scipy import integrate
import numpy as np
def f(x):
    return x**2
result, error = integrate.quad(f, 0, 3)

print("Definite Integration Result:", result)

from scipy import optimize
def func(x):
    return x**2 + 4*x + 4
result = optimize.minimize(func, x0=0)

print("Minimum value at x =", result.x)
print("Minimum function value =", result.fun)

import pandas as pd
data = {
    'Name': ['Ram', 'Priya', 'Sonu', 'Aman'],
    'Age': [25, 30, 22, 28],
    'Address': ['Delhi', 'Kanpur', 'Allahabad', 'Kanpur'],
    'Qualification': ['BSc', 'BA', 'MCA', 'MSc']
}

df = pd.DataFrame(data)

print(df['Name'], df['Qualification'])

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
Y = np.array([2, 4, 5, 4, 5])
model = LinearRegression()
model.fit(X, Y)
Y_pred = model.predict(X)
print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)

plt.scatter(X, Y)
plt.plot(X, Y_pred)
plt.show()